language: ruby
bundler_args: --without yard guard benchmarks release
install:
  - "travis_retry bundle install --without yard guard benchmarks release"
script: "bundle exec rake"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - jruby-19mode
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile